CREATE FUNCTION util.metadataGetClassName(@class TINYINT)
RETURNS NVARCHAR(128)
AS
BEGIN
	RETURN CASE @class
		WHEN 0 THEN 'DATABASE'
		WHEN 1 THEN 'OBJECT_OR_COLUMN'
		WHEN 2 THEN 'PARAMETER'
		WHEN 3 THEN 'SCHEMA'
		WHEN 4 THEN 'DATABASE_PRINCIPAL'
		WHEN 7 THEN 'INDEX'
		WHEN 20 THEN 'DATASPACE'
		WHEN 21 THEN 'PARTITION_FUNCTION'
		WHEN 22 THEN 'DATABASE_FILE'
		WHEN 25 THEN 'CERTIFICATE'
		ELSE NULL
	END;
END;
GO